default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  host: design_db
  username: design
  password: design
  port: 3306

development:
  <<: *local
  database: design_db

test:
  <<: *local
  database: design

production:
  <<: *default
  database: design_production
  username: design
  password: <%= ENV['SEEDS_MANAGER_DATABASE_PASSWORD'] %>
  host: design_db
  port: 3306
