default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: design
  password: design
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: design_db

# test:
#   <<: *default
#   database: design_test

production:
  <<: *default
  database: design_production
  username: design
  password: <%= ENV['DESIGN_DATABASE_PASSWORD'] %>
